## Everything in this section will be available as an environment variable
db_username = "Jane"
db_password = "mypassword"

# The connection name used for secrets lookup in [connections.<name>].
[connections.pets_db] # prod db
url = "sqlite:///pets.db"

# dev db
[connections.pets_bd_dev]
url = "sqlite:///pets.db"

